### ISSUE TITLE
Abschlusspräsentation

### ISSUE THREAD

**Issue by SvenSeemann** [JustusAdam/swt-festivalmanager#76]
Kann es sein, dass die Mailing-Liste down ist/war? Naja, für den Notfall nochmal hier was mit der Mail kam, bzw. hätte kommen sollen ;)
@JustusAdam @fallik @NikolaiKostka @MaxSchwarze @HendricEckelt 

wollte mal nachfragen wie der Stand der Abschlusspräsentation ist. Wäre gut wenn ich da mal was bekomme. (Frau Demuth will das ja in der Abgabe mit dabei haben).

Vielleicht nochmal der Hinweis (weil ich mir grade die Präsentation von einer anderen Gruppe angehört habe):
Zeigt nicht nur die fertige Software, sondern erzählt anfangs auch was zum Team bzw. den Rollen, Projektverlauf und Problemen/Lösungen, oder was es eben  so allgemeines zu sagen gibt.

Achja, Ort/Zeit der Präsentation steht jetzt auch nochmal auf der SWP Webseite.

**Comment by JustusAdam** [comment]
Done
